import os
import pandas as pd
import yaml
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import locale

# Attempt to set locale for Indian number formatting if supported
try:
    locale.setlocale(locale.LC_ALL, 'en_IN')
except:
    pass

def format_inr(number):
    try:
        # Try locale formatting
        return locale.currency(number, symbol=True, grouping=True)
    except:
        # Fallback manual formatting
        s, *d = str(number).partition(".")
        r = ",".join([s[x-2:x] for x in range(-3, -len(s), -2)][::-1] + [s[-3:]])
        return f"₹ {r}{d[0]}{d[1]}"

def load_config():
    config_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'config.yaml')
    with open(config_path, 'r') as file:
        return yaml.safe_load(file)

def generate_email_html(df, current_date, total_items, total_revenue):
    rows_html = ""
    for _, row in df.iterrows():
        risk_color = "#FF4444" if row['risk_level'] == 'HIGH' else "#000000"
        text_color = "#FFFFFF" if row['risk_level'] == 'CRITICAL' else "#000000"
        
        rows_html += f"""
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">{row['store_id']}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">{row['product_id']}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">{row.get('category', 'N/A')}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; background-color: {risk_color}; color: {text_color}; font-weight: bold; text-align: center;">{row['risk_level']}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: right;">{row['current_stock']}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: right;">{row['predicted_7day_demand']:.2f}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: right;">{format_inr(row['revenue_at_risk'])}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: right; font-weight: bold;">{row['recommended_reorder_qty']}</td>
        </tr>
        """

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .header {{ background-color: #FF6B00; color: white; padding: 20px; text-align: center; }}
            .summary {{ margin: 20px 0; padding: 15px; background-color: #f9f9f9; border-left: 5px solid #FF6B00; }}
            .data-table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            .data-table th {{ background-color: #f2f2f2; padding: 12px; text-align: left; border-bottom: 2px solid #ddd; }}
            .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.8em; color: #777; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h2>🚨 MegaMart Supply Chain Alert</h2>
        </div>
        
        <div class="summary">
            <h3>Executive Summary ({current_date})</h3>
            <p><strong>Total Items at Risk:</strong> {total_items}</p>
            <p><strong>Total Revenue at Stake:</strong> {format_inr(total_revenue)}</p>
        </div>

        <h3>Detailed Risk Report</h3>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Store</th>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Risk Level</th>
                    <th>Current Stock</th>
                    <th>Pred. 7-Day Demand</th>
                    <th>Revenue at Risk (₹)</th>
                    <th>Recommended Reorder</th>
                </tr>
            </thead>
            <tbody>
                {rows_html}
            </tbody>
        </table>

        <div class="footer">
            <p>Generated by Predictive Supply Chain Control Tower</p>
            <p>Timestamp: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </div>
    </body>
    </html>
    """
    return html

def main():
    print("🔄 Starting Email Alerts Job...")
    
    # Paths
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_path = os.path.join(base_dir, 'data', 'processed', 'stockout_risk.csv')
    reports_dir = os.path.join(base_dir, 'reports')
    os.makedirs(reports_dir, exist_ok=True)
    
    # 1. LOAD RISK DATA
    try:
        df = pd.read_csv(data_path)
    except FileNotFoundError:
        print(f"❌ Error: Could not find {data_path}. Run predictions first.")
        return

    # Filter for HIGH and CRITICAL risk
    high_risk_df = df[df['risk_level'].isin(['HIGH', 'CRITICAL'])].copy()
    
    if high_risk_df.empty:
        print("✅ No alerts needed. No items are at HIGH or CRITICAL risk.")
        return

    total_items = len(high_risk_df)
    total_revenue = high_risk_df['revenue_at_risk'].sum()
    current_date = datetime.now().strftime("%Y-%m-%d")
    
    print(f"📊 Found {total_items} items at risk, total revenue at stake: {format_inr(total_revenue)}")
    
    # 2. FORMAT HTML EMAIL
    html_content = generate_email_html(high_risk_df, current_date, total_items, total_revenue)
    
    # Save plain-text summary
    summary_path = os.path.join(reports_dir, 'alert_summary.txt')
    with open(summary_path, 'w', encoding='utf-8') as f:
        f.write(f"MegaMart Supply Chain Alert - {current_date}\n")
        f.write(f"Total Items at Risk: {total_items}\n")
        f.write(f"Total Revenue at Stake: {format_inr(total_revenue)}\n")
        f.write("\nItems:\n")
        for _, row in high_risk_df.iterrows():
            f.write(f"- Store: {row['store_id']}, Product: {row['product_id']}, Risk: {row['risk_level']}, Reorder Qty: {row['recommended_reorder_qty']}\n")
    print(f"✅ Saved plain-text summary to {summary_path}")

    # 3. SEND EMAIL
    config = load_config()
    email_config = config.get('email', {})
    
    subject = f"[MegaMart Alert] ⚠️ {total_items} Products at Stockout Risk — {current_date}"
    
    if not email_config.get('enabled', False):
        html_path = os.path.join(reports_dir, 'alert_email.html')
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f"ℹ️ Email sending is disabled in config. HTML saved to {html_path}")
        return

    print("📧 Sending email via SMTP...")
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = email_config.get('sender', 'alerts@megamart.com')
        
        recipients = email_config.get('recipients', [])
        if isinstance(recipients, str):
            recipients = [recipients]
        msg['To'] = ", ".join(recipients)
        
        part = MIMEText(html_content, 'html')
        msg.attach(part)
        
        # Connect and send
        server = smtplib.SMTP(email_config['smtp_server'], email_config['smtp_port'])
        server.starttls()
        
        if email_config.get('username') and email_config.get('password'):
            server.login(email_config['username'], email_config['password'])
            
        server.sendmail(msg['From'], recipients, msg.as_string())
        server.quit()
        print("✅ Email sent successfully!")
        
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        
        # Save HTML as fallback
        html_path = os.path.join(reports_dir, 'alert_email_fallback.html')
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f"ℹ️ Saved HTML to {html_path} as fallback.")

if __name__ == "__main__":
    main()
